name: Build OpenWrt Passwall2

on:
  repository_dispatch:
  workflow_dispatch:

jobs:
  build-passwall2:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Read SDK URL
      id: read-sdk
      run: |
        SDK_URL=$(cat 1.txt)
        echo "SDK_URL=${SDK_URL}" >> $GITHUB_ENV
        echo "Using SDK URL: ${SDK_URL}"

    - name: Install zstd tool
      run: sudo apt-get install -y zstd 

    - name: Download and extract OpenWrt SDK
      run: |
        wget ${{ env.SDK_URL }} -O sdk.tar.zst
        tar -I zstd -xf sdk.tar.zst --strip-components=1
        echo "SDK_DIR=$(pwd)" >> $GITHUB_ENV

    - name: Set up build environment
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libncurses5-dev \
        zlib1g-dev gawk git gettext libssl-dev xsltproc rsync python3 python3-distutils
        
    - name: Add passwall2 to feed
      run: |
        echo "src-git passwall_packages https://github.com/xiaorouji/openwrt-passwall-packages.git;main" >> "feeds.conf.default"
        echo "src-git passwall2 https://github.com/xiaorouji/openwrt-passwall2;main" >> "feeds.conf.default"
        wget  https://github.com/luoyanchen666/passwallaction/edit/main/.config -O ./.config
    - name: Prepare SDK configuration
      run: | 
        # 更新feeds并安装依赖
        ./scripts/feeds update -a
        ./scripts/feeds install -a -f -p passwall_packages
        ./scripts/feeds install -a -f -p passwall2

    - name: will download
      run: |
        make download -j8 V=s
        
    - name: Build passwall2 package
      run: |
        make defconfig
        make   V=s -j$(nproc)
        
    - name: Collect artifacts
      run: |
        mkdir -p artifacts
        find bin -name "*.ipk" -exec cp {} artifacts/ \;
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: passwall2-packages
        path: artifacts/
